Repository helloworld-bedev/study-together, pull requests merged in 2024-10, with the labels that each got.

#16 Feature/9/create answer
  README.md
  src/main/java/helloworld/studytogether/answer/controller/AnswerController.java
  src/main/java/helloworld/studytogether/answer/dto/AnswerDTO.java
  src/main/java/helloworld/studytogether/answer/entity/Answer.java
  src/main/java/helloworld/studytogether/answer/repository/AnswerRepository.java
  src/main/java/helloworld/studytogether/answer/service/AnswerService.java
  src/main/java/helloworld/studytogether/answer/service/AnswerServiceImpl.java
  src/main/java/helloworld/studytogether/config/SecurityConfig.java
Labels: enhancement

#26 HOTFIX : 패키지 구조 변경, 서비스 로직에서 조회항목 userId, questionId 추가
  src/main/java/helloworld/studytogether/answer/entity/Answer.java
  src/main/java/helloworld/studytogether/common/entity/BaseEntity.java
  src/main/java/helloworld/studytogether/common/exception/GlobalExceptionHandler.java
  src/main/java/helloworld/studytogether/questions/controller/QuestionApiController.java
  src/main/java/helloworld/studytogether/questions/dto/AddQuestionRequestDto.java
  src/main/java/helloworld/studytogether/questions/dto/AddQuestionResponseDto.java
  src/main/java/helloworld/studytogether/questions/entity/Question.java
  src/main/java/helloworld/studytogether/questions/repository/QuestionRepository.java
  src/main/java/helloworld/studytogether/questions/service/QuestionService.java
  src/main/java/helloworld/studytogether/questions/service/QuestionServiceImpl.java
  src/main/java/helloworld/studytogether/questions/type/SubjectNames.java
  src/main/java/questions/service/QuestionService.java
Labels: bug

#35 Feature/15/회원정보 조회 수정 기능 구현
  build.gradle
  src/main/java/helloworld/studytogether/answer/repository/AnswerRepository.java
  src/main/java/helloworld/studytogether/dictionary/entity/Dictionary.java
  src/main/java/helloworld/studytogether/questions/repository/QuestionRepository.java
  src/main/java/helloworld/studytogether/rewards/entity/Rewards.java
  src/main/java/helloworld/studytogether/user/dto/CountDTO.java
  src/main/java/helloworld/studytogether/user/dto/UserResponseDTO.java
  src/main/java/helloworld/studytogether/user/entity/Count.java
  src/main/java/helloworld/studytogether/user/entity/User.java
  src/main/java/helloworld/studytogether/user/repository/CountRepository.java
  src/main/java/helloworld/studytogether/user/service/UserService.java
Labels: enhancement

#41 Release: Merge develop into main
  .gitignore
  build.gradle
  qodana.yaml
  src/main/java/helloworld/studytogether/StudyTogetherApplication.java
  src/main/java/helloworld/studytogether/answer/controller/AnswerController.java
  src/main/java/helloworld/studytogether/answer/dto/AnswerDTO.java
  src/main/java/helloworld/studytogether/answer/entity/Answer.java
  src/main/java/helloworld/studytogether/answer/repository/AnswerRepository.java
  src/main/java/helloworld/studytogether/answer/service/AnswerService.java
  src/main/java/helloworld/studytogether/answer/service/AnswerServiceImpl.java
  src/main/java/helloworld/studytogether/common/entity/BaseEntity.java
  src/main/java/helloworld/studytogether/common/exception/CustomException.java
  src/main/java/helloworld/studytogether/common/exception/ErrorCode.java
  src/main/java/helloworld/studytogether/common/exception/ErrorResponse.java
  src/main/java/helloworld/studytogether/common/exception/GlobalExceptionHandler.java
  src/main/java/helloworld/studytogether/config/SecurityConfig.java
  src/main/java/helloworld/studytogether/dictionary/entity/Dictionary.java
  src/main/java/helloworld/studytogether/jwt/filter/CustomLogoutFilter.java
  src/main/java/helloworld/studytogether/jwt/filter/JWTFilter.java
  src/main/java/helloworld/studytogether/jwt/filter/LoginFilter.java
  src/main/java/helloworld/studytogether/jwt/util/JWTUtil.java
  src/main/java/helloworld/studytogether/jwt/util/SecurityUtil.java
  src/main/java/helloworld/studytogether/questions/controller/QuestionApiController.java
  src/main/java/helloworld/studytogether/questions/dto/AddQuestionResponseDto.java
  src/main/java/helloworld/studytogether/questions/dto/GetQuestionResponseDto.java
  src/main/java/helloworld/studytogether/questions/dto/QuestionRequest.java
  src/main/java/helloworld/studytogether/questions/entity/Question.java
  src/main/java/helloworld/studytogether/questions/repository/QuestionRepository.java
  src/main/java/helloworld/studytogether/questions/service/QuestionService.java
  src/main/java/helloworld/studytogether/questions/service/QuestionServiceImpl.java
  src/main/java/helloworld/studytogether/questions/type/SubjectNames.java
  src/main/java/helloworld/studytogether/rewards/entity/Rewards.java
  src/main/java/helloworld/studytogether/token/controller/ReissueController.java
  src/main/java/helloworld/studytogether/token/entity/RefreshToken.java
  src/main/java/helloworld/studytogether/token/repository/RefreshTokenRepository.java
  src/main/java/helloworld/studytogether/token/service/TokenService.java
  src/main/java/helloworld/studytogether/user/controller/AdminController.java
  src/main/java/helloworld/studytogether/user/controller/JoinController.java
  src/main/java/helloworld/studytogether/user/controller/LogoutController.java
  src/main/java/helloworld/studytogether/user/controller/UserController.java
  src/main/java/helloworld/studytogether/user/dto/AdminUpdateRequestDTO.java
  src/main/java/helloworld/studytogether/user/dto/CountDTO.java
  src/main/java/helloworld/studytogether/user/dto/CustomUserDetails.java
  src/main/java/helloworld/studytogether/user/dto/UserResponseDTO.java
  src/main/java/helloworld/studytogether/user/dto/UserUpdateDTO.java
  src/main/java/helloworld/studytogether/user/entity/Count.java
  src/main/java/helloworld/studytogether/user/entity/User.java
  src/main/java/helloworld/studytogether/user/repository/CountRepository.java
  src/main/java/helloworld/studytogether/user/service/AdminService.java
  src/main/java/helloworld/studytogether/user/service/UserService.java
  src/main/resources/static/images/study_erd.png
  src/main/resources/static/images/study_erd_v2.png
  src/main/resources/static/images/study_erd_v3.png
  src/main/resources/static/images/wireframe.png
  src/test/java/helloworld/studytogether/jwt/JWTFilterTest.java
  src/test/java/helloworld/studytogether/user/controller/StudyTogetherApplicationTests.java
  src/test/java/helloworld/studytogether/user/controller/UserControllerTest.java
Labels: release

#44 Feature/#40 update questions
  src/main/java/helloworld/studytogether/common/util/ImageUtil.java
  src/main/java/helloworld/studytogether/common/util/SecurityUtil.java
  src/main/java/helloworld/studytogether/questions/controller/QuestionApiController.java
  src/main/java/helloworld/studytogether/questions/dto/UpdateQuestionRequest.java
  src/main/java/helloworld/studytogether/questions/dto/UpdateQuestionResponse.java
  src/main/java/helloworld/studytogether/questions/entity/Question.java
  src/main/java/helloworld/studytogether/questions/service/QuestionService.java
  src/main/java/helloworld/studytogether/questions/service/QuestionServiceImpl.java
Labels: enhancement

#45 feature/46/답변 채택 기능
  src/main/java/helloworld/studytogether/answer/controller/AnswerController.java
  src/main/java/helloworld/studytogether/answer/dto/AnswerDTO.java
  src/main/java/helloworld/studytogether/answer/entity/Answer.java
  src/main/java/helloworld/studytogether/answer/repository/AnswerRepository.java
  src/main/java/helloworld/studytogether/answer/service/AnswerService.java
  src/main/java/helloworld/studytogether/answer/service/AnswerServiceImpl.java
  src/main/java/helloworld/studytogether/comment/controller/CommentController.java
  src/main/java/helloworld/studytogether/comment/dto/CommentDTO.java
  src/main/java/helloworld/studytogether/comment/entity/Comment.java
  src/main/java/helloworld/studytogether/comment/repository/CommentRepository.java
  src/main/java/helloworld/studytogether/comment/service/CommentService.java
  src/main/java/helloworld/studytogether/questions/controller/QuestionApiController.java
  src/main/java/helloworld/studytogether/questions/entity/Question.java
  src/main/java/helloworld/studytogether/questions/repository/QuestionRepository.java
  src/main/java/helloworld/studytogether/questions/service/QuestionService.java
  src/main/java/helloworld/studytogether/questions/service/QuestionServiceImpl.java
  src/main/java/helloworld/studytogether/user/entity/Count.java
  src/main/java/helloworld/studytogether/user/repository/CountRepository.java
Labels: enhancement

#58 회원가입 오류 수정
  src/main/java/helloworld/studytogether/config/SecurityConfig.java
  src/main/java/helloworld/studytogether/jwt/filter/JWTFilter.java
Labels: bug

#54 Feature/delete question
  src/main/java/helloworld/studytogether/common/permission/OwnedResource.java
  src/main/java/helloworld/studytogether/common/permission/PermissionValidator.java
  src/main/java/helloworld/studytogether/common/util/SecurityUtil.java
  src/main/java/helloworld/studytogether/questions/controller/QuestionApiController.java
  src/main/java/helloworld/studytogether/questions/entity/Question.java
  src/main/java/helloworld/studytogether/questions/service/QuestionService.java
  src/main/java/helloworld/studytogether/questions/service/QuestionServiceImpl.java
  src/main/resources/static/images/study_erd_v4.png
Labels: documentation, enhancement

#59 Fix: RequestMatchers 수정 부분 반영
  src/main/java/helloworld/studytogether/config/SecurityConfig.java
  src/main/java/helloworld/studytogether/jwt/filter/JWTFilter.java
Labels: bug

#60 Merge to main from develop
  src/main/java/helloworld/studytogether/answer/dto/AnswerDTO.java
  src/main/java/helloworld/studytogether/answer/entity/Answer.java
  src/main/java/helloworld/studytogether/answer/service/AnswerServiceImpl.java
  src/main/java/helloworld/studytogether/comment/controller/CommentController.java
  src/main/java/helloworld/studytogether/comment/dto/CommentDTO.java
  src/main/java/helloworld/studytogether/comment/entity/Comment.java
  src/main/java/helloworld/studytogether/comment/service/CommentService.java
  src/main/java/helloworld/studytogether/common/exception/ErrorCode.java
  src/main/java/helloworld/studytogether/common/exception/GlobalExceptionHandler.java
  src/main/java/helloworld/studytogether/common/permission/OwnedResource.java
  src/main/java/helloworld/studytogether/common/permission/PermissionValidator.java
  src/main/java/helloworld/studytogether/common/util/SecurityUtil.java
  src/main/java/helloworld/studytogether/config/SecurityConfig.java
  src/main/java/helloworld/studytogether/forbidden/service/ForbiddenService.java
  src/main/java/helloworld/studytogether/jwt/filter/JWTFilter.java
  src/main/java/helloworld/studytogether/questions/controller/QuestionApiController.java
  src/main/java/helloworld/studytogether/questions/dto/AddQuestionResponseDto.java
  src/main/java/helloworld/studytogether/questions/dto/QuestionRequest.java
  src/main/java/helloworld/studytogether/questions/entity/Question.java
  src/main/java/helloworld/studytogether/questions/service/QuestionService.java
  src/main/java/helloworld/studytogether/questions/service/QuestionServiceImpl.java
  src/main/resources/static/images/study_erd_v4.png
Labels: release

#63 Merge to main from develop
  src/main/java/helloworld/studytogether/forbidden/service/ForbiddenService.java
  src/main/java/helloworld/studytogether/user/dto/CountDTO.java
  src/main/java/helloworld/studytogether/user/service/CountService.java
  src/main/java/helloworld/studytogether/user/service/UserService.java
Labels: documentation
